# test/simulate_pipeline.py
import sys
import os
import shutil
import yaml

# 将 src 加入路径
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../src")))

from core.manager import ProjectManager
from providers.base import LLMResult


# === 1. 定义 Mock Provider ===
class MockProvider:
    """
    模拟 LLM 行为，不消耗 Token。
    根据 Prompt 中的关键词返回不同格式的数据，以骗过 Pipeline 的解析逻辑。
    """

    def generate(self, system: str, prompt: str, **kwargs) -> LLMResult:
        # 1. 针对 Step 01 Ideation (Layer 1 JSON)
        # 关键词匹配 prompts.yaml 中的 "构思 {{ num_ideas }} 个... 请输出一个纯 JSON 列表"
        if "构思" in prompt and "JSON" in prompt:
            # 返回符合 Step 01 解析要求的 JSON 列表
            return LLMResult(
                text='[{"title": "Mock Book", "core_concept": "Test Concept"}]'
            )

        # 2. 针对 Step 02 Outline (Layer 1 Structure JSON)
        if "分卷规划" in prompt:
            return LLMResult(
                text='[{"volume_id": 1, "title": "Mock Vol 1", "summary": "Summary 1"}]'
            )

        # 3. 针对 Step 03 Bible (Layer 1 Extraction JSON)
        if "提取出需要进行详细设定的清单" in prompt:
            return LLMResult(
                text='{"characters": ["CharA"], "factions": ["FactionB"], "locations": ["LocC"], "system": ["SysD"]}'
            )

        # 4. 针对 Step 04a Scene Plan (Layer 1 Extraction JSON)
        if "分场/章节清单" in prompt:
            return LLMResult(
                text='[{"id": 1, "title": "Scene 1", "summary": "Scene Summary", "characters": ["CharA"]}]'
            )

        # 5. 针对 Evaluation/Analysis (Markdown Report)
        if "评估报告" in prompt or "分析" in prompt:
            return LLMResult(text="# Mock Analysis Report\n\n- Risk: Low\n- Score: 90")

        # 默认：返回 Markdown 文本 (用于 Expansion/Drafting)
        return LLMResult(
            text="# Mock Content\n\nThis is generated by MockProvider.\nSome dummy content for testing."
        )

    def stream_generate(self, system: str, prompt: str, **kwargs):
        # === 核心修复 ===
        # 复用 generate 的逻辑来获取正确格式的文本 (JSON 或 Markdown)
        full_result = self.generate(system, prompt, **kwargs)
        full_text = full_result.text

        # 模拟流式：将完整文本切片返回
        chunk_size = 5  # 每次返回 5 个字符
        for i in range(0, len(full_text), chunk_size):
            yield full_text[i : i + chunk_size]


# === 2. 模拟运行 ===
def run_simulation():
    print("🚀 Starting Pipeline Simulation (Dry Run)...")

    # 创建临时配置
    test_run_dir = "runs/test_simulation"
    if os.path.exists(test_run_dir):
        try:
            shutil.rmtree(test_run_dir)
        except Exception as e:
            print(f"Warning: Could not clean up {test_run_dir}: {e}")

    config_path = "config/config.yaml"
    if not os.path.exists(config_path):
        config_path = "config/config_template.yaml"
        if not os.path.exists(config_path):
            print("❌ Config not found, skipping.")
            return

    # 初始化 Manager
    manager = ProjectManager(config_path)
    # 强制替换为 Mock Provider
    manager.provider = MockProvider()

    # 强制覆盖配置：关闭 HITL 交互模式，避免测试阻塞
    manager.config["workflow"] = {
        "interactive": False,
        "branching": {"enabled": True, "num_candidates": 1},
    }

    # 强制修改输出目录
    manager.run_dir = test_run_dir
    os.makedirs(manager.run_dir, exist_ok=True)
    manager.store.root_dir = test_run_dir
    manager.state.run_dir = test_run_dir
    manager.state.save()

    print(f"📂 Run ID: {manager.run_id} (Mocked)")
    print(f"📂 Output Dir: {test_run_dir}")

    try:
        # Step 1: Ideation
        print("\n[1/5] Running Ideation...")
        manager.run_ideation()

        # Step 2: Outline
        print("\n[2/5] Running Outline...")
        manager.run_outline()

        # Step 3: Bible
        print("\n[3/5] Running Bible...")
        manager.run_bible()

        # Step 4a: Scene Plan
        print("\n[4/5] Running Scene Plan...")
        manager.init_scenes()

        # Step 4b: Drafting
        print("\n[5/5] Running Drafting...")
        manager.run_drafting_loop()

        print("\n✅ Simulation Completed Successfully!")
        print(f"Check outputs in: {manager.run_dir}")

    except Exception as e:
        print(f"\n❌ Simulation Failed: {e}")
        import traceback

        traceback.print_exc()


if __name__ == "__main__":
    run_simulation()
